name: Build motion for various architectures and distros
on:
  workflow_dispatch:

env:
  VERSION: 4.7
  EMAIL: tosiara@users.noreply.github.com

jobs:
  buildmotions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: buildmotions.sh
        run: sudo -E ./buildmotions.sh
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: debs
          path: ./*.deb
