name: Build
on:
  workflow_dispatch:

env:
  VERSION: 4.7
  EMAIL: tosiara@users.noreply.github.com

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ubuntu
        run: |
            sudo apt-get update
            sudo apt-get install -y binfmt-support qemu-user-static
            sudo -E ./build-distro.sh "ubuntu:xenial"
            sudo -E ./build-distro.sh "ubuntu:bionic"
            sudo -E ./build-distro.sh "ubuntu:focal"
            sudo -E ./build-distro.sh "ubuntu:jammy"
            sudo -E ./build-distro.sh "ubuntu:noble"
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_debs
          path: ./*.deb
  
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: debian
        run: |
            sudo apt-get update
            sudo apt-get install -y binfmt-support qemu-user-static
            sudo -E ./build-distro.sh "debian:stretch"
            sudo -E ./build-distro.sh "debian:buster"
            sudo -E ./build-distro.sh "debian:bullseye"
            sudo -E ./build-distro.sh "debian:bookworm"
            sudo -E ./build-distro.sh "debian:trixie"
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: debian_debs
          path: ./*.deb
  
