name: Build
on:
  workflow_dispatch:

env:
  VERSION: 4.7
  EMAIL: tosiara@users.noreply.github.com

jobs:

  ubuntu-bionic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ubuntu-bionic
        run: |
            sudo apt-get update
            sudo apt-get install -y binfmt-support qemu-user-static
            sudo -E ./build-distro.sh "ubuntu:bionic"
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_bionic_debs
          path: ./*.deb

  ubuntu-focal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ubuntu-focal
        run: |
            sudo apt-get update
            sudo apt-get install -y binfmt-support qemu-user-static
            sudo -E ./build-distro.sh "ubuntu:focal"
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_focal_debs
          path: ./*.deb

  ubuntu-jammy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ubuntu-jammy
        run: |
            sudo apt-get update
            sudo apt-get install -y binfmt-support qemu-user-static
            sudo -E ./build-distro.sh "ubuntu:jammy"
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_jammy_debs
          path: ./*.deb

  ubuntu-noble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ubuntu-noble
        run: |
            sudo apt-get update
            sudo apt-get install -y binfmt-support qemu-user-static
            sudo -E ./build-distro.sh "ubuntu:noble"
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_noble_debs
          path: ./*.deb
  
  debian-buster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: debian-buster
        run: |
            sudo apt-get update
            sudo apt-get install -y binfmt-support qemu-user-static
            sudo -E ./build-distro.sh "debian:buster"
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: debian_buster_debs
          path: ./*.deb

  debian-bullseye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: debian-bullseye
        run: |
            sudo apt-get update
            sudo apt-get install -y binfmt-support qemu-user-static
            sudo -E ./build-distro.sh "debian:bullseye"
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: debian_bullseye_debs
          path: ./*.deb
  
  debian-bookworm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: debian-bookworm
        run: |
            sudo apt-get update
            sudo apt-get install -y binfmt-support qemu-user-static
            sudo -E ./build-distro.sh "debian:bookworm"
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: debian_bookworm_debs
          path: ./*.deb
  
  debian-trixie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: debian-trixie
        run: |
            sudo apt-get update
            sudo apt-get install -y binfmt-support qemu-user-static
            sudo -E ./build-distro.sh "debian:trixie"
      - name: Save debs
        uses: actions/upload-artifact@v4
        with:
          name: debian_trixie_debs
          path: ./*.deb
  
