name: buildmotions.sh
on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: 4.7.0

jobs:
  build_amd64_ubuntu_noble:
    runs-on: ubuntu-24.04
    env:
      PLATFORM: amd64/ubuntu:noble
    steps:
      - uses: actions/checkout@v4
      - name: entrypoint.sh
        run: sudo -E ./entrypoint.sh
