name: CI
on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_amd64_ubuntu_noble:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          export VERSION="4.7.0"
          export PLATFORM="amd64/ubuntu:noble"
          sudo ./entrypoint.sh
